


# By default, Goldmark does not render raw HTML and potentially dangerous links. 
# If you have lots of inline HTML and/or JavaScript, you may need to turn this on.

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true

[outputs]
    # home = ['html', 'rss', 'print']
    # page = ['html', 'rss', 'print']
    # section = ['html', 'rss', 'print']
    home = ['html', 'rss']
    page = ['html', 'rss']
    section = ['html', 'rss']

[params]
    languageCode = 'de-DE'
    languageName = 'Deutsch'
    themeVariant = ['dark', 'light']

    title = "Introduktion till datorer"

    disableLandingPageButton = true
    collapsibleMenu = true
    showVisitedLinks = true
    disableInlineCopyToClipBoard = true
    disableRootBreadcrumb = true
    # disableNextPrev = true
    editURL = 'https://github.com/McShelby/hugo-theme-relearn/edit/main/docs/content/${FilePath}'
    # additionalContentLanguage = []
    # disableLanguageSwitchingButton = true

    githubIcon = "<i class='fab fa-github'></i>"

    mandatoryIcon = "<i class='fa fa-exclamation-triangle'></i>"

    higherGradeIcon = "<i class='fas fa-star'></i>"

    # Changing the Theme variant switcher menu icon
    #
    # https://github.com/McShelby/hugo-theme-relearn/issues/1104

    [[params.sidebarfootermenus]]
        type = 'divider'

    [[params.sidebarfootermenus]]
        identifier = 'footercontrols'
        type = 'custom'

        [[params.sidebarfootermenus.elements]]
            type = 'languageswitcher'

        [[params.sidebarfootermenus.elements]]
            type = 'variantswitcher'
            icon = 'droplet'

        [[params.sidebarfootermenus.elements]]
            type = 'historyclearer'
